port: /dev/ttyDXL

joint_order: [j1, j2, j3, j4, j5, j6, gripper]
sleep_positions: [-1.57, 1.91, -2.83, -2.46, 0.00, -1.570, 0.0]

joint_state_publisher:
  update_rate: 100
  publish_states: true
  topic_name: joint_states

groups:
  arm: [j1, j2, j3, j4, j5, j6]

grippers:
  gripper:
    type: rack_and_pinion
    pitch_radius: 0.0127
    left_finger: left_finger
    right_finger: right_finger
    calibrate: true

shadows:

sisters:

motors:
  j1:
    ID: 1
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  j2:
    ID: 2
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 782
    Max_Position_Limit: 3331
    Secondary_ID: 255

  j3:
    ID: 3
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 90
    Max_Position_Limit: 4000
    Secondary_ID: 255

  j4:
    ID: 4
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  j5:
    ID: 5
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 1
    Velocity_Limit: 131
    Min_Position_Limit: 17
    Max_Position_Limit: 4000
    Secondary_ID: 255

  j6:
    ID: 6
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Secondary_ID: 255

  gripper:
    ID: 7
    Baud_Rate: 3
    Return_Delay_Time: 0
    Drive_Mode: 0
    Velocity_Limit: 131
    Min_Position_Limit: 0
    Max_Position_Limit: 4095
    Current_Limit: 300
    Secondary_ID: 255
