/$(var robot_name):
  controller_manager:
    ros__parameters:
      update_rate: 10 # Hz
      arm_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      gripper_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
/$(var robot_name):
  arm_controller:
    ros__parameters:
      joints:
        - waist
        - shoulder
        - elbow
        - wrist_angle
      command_interfaces:
        - position
      state_interfaces:
        - position
      state_publish_rate: 50.0 # Hz
      action_monitor_rate: 20.0 # Hz
      constraints:
        stopped_velocity_tolerance: 0.02
        goal_time: 1.0
/$(var robot_name):
  gripper_controller:
    ros__parameters:
      joints:
        - left_finger
      command_interfaces:
        - position
      state_interfaces:
        - position
/$(var robot_name):
  joint_state_broadcaster:
    ros__parameters:
      joints:
        - waist
        - shoulder
        - elbow
        - wrist_angle
        - gripper
        - left_finger
