sensors:
  - kinect_pointcloud
  - kinect_depthimage
kinect_pointcloud:
  filtered_cloud_topic: filtered_cloud
  max_range: 5.0
  max_update_rate: 1.0
  padding_offset: 0.1
  padding_scale: 1.0
  point_cloud_topic: /head_mount_kinect/depth_registered/points
  point_subsample: 1
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
kinect_depthimage:
  far_clipping_plane_distance: 5.0
  filtered_cloud_topic: filtered_cloud
  image_topic: /head_mount_kinect/depth_registered/image_raw
  max_update_rate: 1.0
  near_clipping_plane_distance: 0.3
  padding_offset: 0.03
  padding_scale: 4.0
  queue_size: 5
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  shadow_threshold: 0.2