controller_names:
  - /dx400/arm_controller
  - /dx400/gripper_controller

/dx400/arm_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - j1
    - j2
    - j3
    - j4
    - j5
    - j6
  action_ns: follow_joint_trajectory
  default: true
/dx400/gripper_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - left_finger
    - right_finger
    - gripper
  action_ns: follow_joint_trajectory
  default: true