controller_names:
  - /miv_arm/arm_controller
  # - /miv_arm/gripper_controller

/miv_arm/arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - waist
    - shoulder
    - elbow
    - forearm_roll
    - wrist_angle
    - wrist_rotate

# /miv_arm/gripper_controller:
#   action_ns: follow_joint_trajectory
#   type: FollowJointTrajectory
#   default: true
#   joints:
#     - left_finger
