# This file is used to customize the initial operating modes of all joint groups and individual joints in a robot.
# It should be placed in the 'config' directory of any ROS package that builds ontop of the interbotix_xs_sdk.
# Example values are shown as well. All parameters are mandatory unless stated otherwise

port: /dev/ttyDXL_awx250s                             # Optional; specifies the USB port that connects to the U2D2;
                                              # if specified, it overwrites the port in the 'motor_configs' yaml file.
                                              # if the 'port' parameter and its value are left out, the port in the 'motor_configs' yaml file is used.
                                              # if the 'port' parameter is specified but the value is not, it defaults to '/dev/ttyDXL'

groups:                                       # Optional; specify initial Operating Modes for all joint groups (as detailed in the 'motor_configs' yaml file under 'groups')
  arm:                                        # Example joint group name
    operating_mode: position                  # Optional; refer to the 'OperatingModes' Service description file in the 'srv' directory for the seven modes; defaults to 'position'
    profile_type: time                        # Optional; refer to the 'OperatingModes' Service description file in the 'srv' directory for the two profile types; defaults to 'velocity'
    profile_velocity: 2000                    # Optional; refer to the 'OperatingModes' Service description file in the 'srv' directory for a description; defaults to '0'
    profile_acceleration: 1000                # Optional; refer to the 'OperatingModes' Service description file in the 'srv' directory for a description; defaults to '0'
    torque_enable: true                       # Optional; whether the motors in this group should be torqued on or off by default; defaults to 'true'

singles:                                      # Optional; specify the Operating Mode for individual joints (any joint specified in the 'motor_configs' yaml file); parameters follow the same structure as above
  gripper:
    operating_mode: pwm
    torque_enable: true
