port: /dev/ttyDXL

groups:
  arm:
    operating_mode: position
    profile_type: time
    profile_velocity: 2000
    profile_acceleration: 300
    torque_enable: true

singles:
  gripper:
    operating_mode: linear_position
    profile_type: velocity
    profile_velocity: 131
    profile_acceleration: 15
    torque_enable: true
